### ISSUE TITLE
panic: runtime error: slice bounds out of range [1390:1386]

### ISSUE THREAD

**Issue by Denchick** [pg-sharding/spqr#82]
**Describe the bug**
```
panic: runtime error: slice bounds out of range [1390:1386]

goroutine 87 [running]:
github.com/jackc/chunkreader/v2.(*ChunkReader).Next(0xc00041c940?, 0x5?)
        /Users/denchick/go/pkg/mod/github.com/jackc/chunkreader/v2@v2.0.1/chunkreader.go:61 +0x365
github.com/jackc/pgproto3/v2.(*Frontend).Receive(0xc000512400)
        /Users/denchick/go/pkg/mod/github.com/jackc/pgproto3/v2@v2.3.0/frontend.go:84 +0x128
github.com/pg-sharding/spqr/pkg/conn.(*PostgreSQLInstance).Receive(0xc000131cc0?)
        /Users/denchick/Code/spqr/pkg/conn/instance.go:73 +0x1d
github.com/pg-sharding/spqr/router/pkg/datashard.(*Conn).Receive(0x0?)
        /Users/denchick/Code/spqr/router/pkg/datashard/datashard.go:103 +0x28
github.com/pg-sharding/spqr/router/pkg/server.(*MultiShardServer).Receive.func1.1(0x0)
        /Users/denchick/Code/spqr/router/pkg/server/multishard.go:121 +0x72
created by github.com/pg-sharding/spqr/router/pkg/server.(*MultiShardServer).Receive.func1
        /Users/denchick/Code/spqr/router/pkg/server/multishard.go:119 +0xe5
```

**To Reproduce**

```
log_level: 'DEBUG5'
host: 'localhost'
router_port: '6432'
admin_console_port: '7432'
grpc_api_port: '7000'
router_mode: PROXY
show_notice_messages: true
init_sql: "init.sql"
frontend_tls:
  sslmode: disable
frontend_rules:
  - usr: sbtest
    db: sbtest
    pool_mode: TRANSACTION
    auth_rule:
      auth_method: ok
backend_rules:
  - usr: sbtest
    db: sbtest
    pool_discard: true
    pool_rollback: true
    auth_rule:
      auth_method: md5
      password: password
shards:
  shard01:
    db: sbtest
    usr: sbtest
    pwd: password
    type: DATA
    tls:
      sslmode: "require"
      root_cert_file: "/Users/denchick/.postgresql/root.crt"
    hosts:
      - 'sas-xhxplfw3lnnqbf5c.db.yandex.net:6432'
  shard02:
    db: sbtest
    usr: sbtest
    pwd: password
    type: DATA
    tls:
      sslmode: "require"
      root_cert_file: "/Users/denchick/.postgresql/root.crt"
    hosts:
      - 'sas-v0df2vny5r5x5u77.db.yandex.net:6432'
```

sysbench  --threads=1  --table_size=1000 --tables=10 --pgsql-host=localhost --pgsql-port=6432 --db-driver=pgsql --pgsql-user=sbtest --pgsql-password=password --pgsql-db=sbtest --pgsql-sslmode=disable --verbosity=5 --db-debug=on --db-ps-mode=disable /usr/local/share/sysbench/oltp_read_write.lua cleanup
sysbench 1.1.0-df89d34 (using bundled LuaJIT 2.1.0-beta3)
