### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Denchick** [pg-sharding/spqr#83]
**Describe the bug**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45a927d]

goroutine 40 [running]:
github.com/pg-sharding/spqr/router/pkg/parser.(*QParser).Stmt(0xc000126058)
        /Users/denchick/Code/spqr/router/pkg/parser/qparser.go:23 +0x1d
github.com/pg-sharding/spqr/router/pkg/qrouter.(*ProxyQrouter).Route(0xc000126000, {0x4a10790, 0xc00003c0c8})
        /Users/denchick/Code/spqr/router/pkg/qrouter/proxy_routing.go:311 +0x4c
github.com/pg-sharding/spqr/router/pkg/rulerouter.(*RelayStateImpl).Reroute(0xc0004e4240)
        /Users/denchick/Code/spqr/router/pkg/rulerouter/relay.go:214 +0x1aa
github.com/pg-sharding/spqr/router/pkg/rulerouter.(*RelayStateImpl).PrepareRelayStep(0xc0004e4240, {0x4a1aac0, 0xc0004e0090}, {0x4a12f60, 0xc00011e4ec})
        /Users/denchick/Code/spqr/router/pkg/rulerouter/relay.go:508 +0x165
github.com/pg-sharding/spqr/router/pkg/rulerouter.(*RelayStateImpl).ProcessMessage(0xc0004e4240, {0x4a0e660, 0xc0004b84c0}, 0x0?, 0x0?, {0x4a12f60?, 0xc00011e4ec?})
        /Users/denchick/Code/spqr/router/pkg/rulerouter/relay.go:549 +0x69
github.com/pg-sharding/spqr/router/pkg.Frontend.func1({0x4a1aac0, 0xc0004e0090}, 0xc0000fbea8, {0x4a18938?, 0xc0004e4240?}, {0x4a12f60, 0xc00011e4ec})
        /Users/denchick/Code/spqr/router/pkg/frontend.go:211 +0x267
github.com/pg-sharding/spqr/router/pkg.Frontend({0x4a191a0?, 0xc000126000}, {0x4a1aac0, 0xc0004e0090}, {0x4a12f60?, 0xc00011e4ec}, 0xc0002fc000)
        /Users/denchick/Code/spqr/router/pkg/frontend.go:291 +0x56c
github.com/pg-sharding/spqr/router/pkg.(*InstanceImpl).serv(0xc0001223c0, {0x4a13a00, 0xc0004a6040})
        /Users/denchick/Code/spqr/router/pkg/instance.go:130 +0x114
github.com/pg-sharding/spqr/router/pkg.(*InstanceImpl).Run.func3()
        /Users/denchick/Code/spqr/router/pkg/instance.go:163 +0x29
created by github.com/pg-sharding/spqr/router/pkg.(*InstanceImpl).Run
        /Users/denchick/Code/spqr/router/pkg/instance.go:162 +0x34a
```

**To Reproduce**
```
log_level: 'DEBUG5'
host: 'localhost'
router_port: '6432'
admin_console_port: '7432'
grpc_api_port: '7000'
router_mode: PROXY
show_notice_messages: true
init_sql: "init.sql"
frontend_tls:
  sslmode: disable
frontend_rules:
  - usr: sbtest
    db: sbtest
    pool_mode: TRANSACTION
    auth_rule:
      auth_method: ok
backend_rules:
  - usr: sbtest
    db: sbtest
    pool_discard: true
    pool_rollback: true
    auth_rule:
      auth_method: md5
      password: password
shards:
  shard01:
    db: sbtest
    usr: sbtest
    pwd: password
    type: DATA
    tls:
      sslmode: "require"
      root_cert_file: "/Users/denchick/.postgresql/root.crt"
    hosts:
      - 'sas-xhxplfw3lnnqbf5c.db.yandex.net:6432'
  shard02:
    db: sbtest
    usr: sbtest
    pwd: password
    type: DATA
    tls:
      sslmode: "require"
      root_cert_file: "/Users/denchick/.postgresql/root.crt"
    hosts:
      - 'sas-v0df2vny5r5x5u77.db.yandex.net:6432'
```

sysbench  --threads=1  --table_size=1000 --tables=10 --pgsql-host=localhost --pgsql-port=6432 --db-driver=pgsql --pgsql-user=sbtest --pgsql-password=password --pgsql-db=sbtest --pgsql-sslmode=disable --verbosity=5 --db-debug=on --db-ps-mode=disable /usr/local/share/sysbench/oltp_read_write.lua run
